#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Write the running API's OpenAPI document to openapi.json at the repository
# root, as the deliverables ask.
#
#   ./scripts/export_openapi.sh
#   API_BASE_URL=http://localhost:8080 ./scripts/export_openapi.sh
#
# The document is generated by the API from its own endpoints and XML comments,
# so exporting it from a running instance is the only way to keep the committed
# copy honest. The CI workflow runs this and fails if the result differs from
# what is committed.
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ -f "${REPO_ROOT}/.env" ]]; then
  # shellcheck disable=SC1091
  set -a && source "${REPO_ROOT}/.env" && set +a
fi

API_BASE_URL="${API_BASE_URL:-http://localhost:${API_HOST_PORT:-8080}}"
OUTPUT="${1:-${REPO_ROOT}/openapi.json}"

echo "fetching ${API_BASE_URL}/openapi/v1.json"
curl -fsS "${API_BASE_URL}/openapi/v1.json" |
  python3 -c 'import json,sys; json.dump(json.load(sys.stdin), sys.stdout, indent=2, sort_keys=True); print()' \
    > "${OUTPUT}"

echo "wrote ${OUTPUT}"
python3 - "${OUTPUT}" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as handle:
    document = json.load(handle)

print(f"  openapi   : {document['openapi']}")
print(f"  title     : {document['info']['title']} {document['info']['version']}")
print(f"  paths     : {len(document['paths'])}")
print(f"  schemas   : {len(document.get('components', {}).get('schemas', {}))}")
for path in sorted(document["paths"]):
    methods = ", ".join(sorted(m.upper() for m in document["paths"][path]))
    print(f"    {methods:8s} {path}")
PY
