#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Write the running API's OpenAPI document to openapi.json at the repository
# root, as the deliverables ask.
#
#   ./scripts/export_openapi.sh
#   API_BASE_URL=http://localhost:8080 ./scripts/export_openapi.sh
#
# The document is generated by the API from its own endpoints and XML comments,
# so exporting it from a running instance is the only way to keep the committed
# copy honest. The CI workflow runs this and fails if the result differs from
# what is committed.
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Load .env, but let a real environment variable win.
#
# `set -a && source .env` does the opposite: it overwrites what the caller
# exported. That is wrong here and it wasted a debugging session — running this
# against the deployed API with the AWS client secrets exported still
# authenticated with the local development secrets from .env, got a 401 with an
# empty body, and failed with a JSON decode error that said nothing about the
# real cause. Docker Compose resolves the same conflict the same way: the
# environment beats the file.
if [[ -f "${REPO_ROOT}/.env" ]]; then
  while IFS='=' read -r env_key env_value; do
    [[ "${env_key}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    # Already set by the caller, so leave it alone. `${!k+x}` is true for a
    # variable that is set even when its value is empty.
    [[ -n "${!env_key+x}" ]] && continue
    export "${env_key}=${env_value}"
  done < "${REPO_ROOT}/.env"
  unset env_key env_value
fi

API_BASE_URL="${API_BASE_URL:-http://localhost:${API_HOST_PORT:-8080}}"
OUTPUT="${1:-${REPO_ROOT}/openapi.json}"

echo "fetching ${API_BASE_URL}/openapi/v1.json"
# Single quotes on purpose: the Python below must reach the interpreter as
# written, with no shell expansion. SC2016 warns about exactly the thing that is
# intended here.
# shellcheck disable=SC2016
curl -fsS "${API_BASE_URL}/openapi/v1.json" |
  python3 -c '
import json
import sys

document = json.load(sys.stdin)

# Canonicalise `servers`. ASP.NET Core derives it from the request host, so the
# document a developer exports carries whatever port their .env happens to map —
# `http://localhost:58080/` on a machine that remapped it, `:8080` on a default
# one. That made the committed artifact depend on who exported it, and CI failed
# the diff for a reason that had nothing to do with the API contract.
#
# The value is not meaningful for a locally exported spec anyway: the deployed
# API lives behind a domain, not localhost. Pinning it to the documented default
# keeps the file reproducible from any machine.
document["servers"] = [{"url": "http://localhost:8080/"}]

json.dump(document, sys.stdout, indent=2, sort_keys=True)
print()
' > "${OUTPUT}"

echo "wrote ${OUTPUT}"
python3 - "${OUTPUT}" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as handle:
    document = json.load(handle)

print(f"  openapi   : {document['openapi']}")
print(f"  title     : {document['info']['title']} {document['info']['version']}")
print(f"  paths     : {len(document['paths'])}")
print(f"  schemas   : {len(document.get('components', {}).get('schemas', {}))}")
for path in sorted(document["paths"]):
    methods = ", ".join(sorted(m.upper() for m in document["paths"][path]))
    print(f"    {methods:8s} {path}")
PY
